--- !ruby/object:VR_ENV
vr_yaml_file: "/home/yuri/visualruby/diploma/.vr_settings.yaml"
width: 1424
height: 758
panel_pos: 360
notebook_panel_position: 441
run_command_line: ruby main.rb
open_files:
- "/home/yuri/visualruby/diploma/src/ZKP.rb"
- "/home/yuri/visualruby/diploma/lib/curve.rb"
open_folders:
- "/home/yuri/visualruby/diploma"
- "/home/yuri/visualruby/diploma/src"
- "/home/yuri/visualruby/diploma/src/glade"
current_file: "/home/yuri/visualruby/diploma/lib/curve.rb"
current_line: 110
rdoc_command_line: rdoc -x README
browser: firefox
backup_path: "/home/eric"
tab_spaces: 2
glade_path: glade-3
font_name: Monospace 10
